### ISSUE TITLE
how to use this bosh release

### ISSUE THREAD

**Issue by poblin-orange** [18F/newrelic-boshrelease#6]
Hello,
i just installed the bosh release with my license key.
Bosh release deployment is up.
Missing a step in README to use ? Must registrer as a service broker ?
thks

**Comment by jhunt** [comment]
This is an add-on BOSH release, to be used in conjunction with other BOSH releases.  It only adds monitoring to the mix.

**Comment by poblin-orange** [comment]
got it thks
