### ISSUE TITLE
Release tarballs are not valid bosh releases

### ISSUE THREAD

**Issue by claudio-benfatto** [18F/newrelic-boshrelease#8]
Hello,

first of all thank you for the very useful release.

I've noticed that the release tarballs listed here: [Release tarballs](https://github.com/cloudfoundry-community/newrelic-boshrelease/releases) , aren't actually proper bosh releases, directly uploadable to bosh.

Would it make sense, given the nature of the project, to save into the github releases section the result of the `bosh create release {manifest_path} --with-tarball` command?

Thanks
Claudio

**Comment by jhunt** [comment]
This BOSH release is now running builds out of Stark & Wayne concourse, over here: https://ci.starkandwayne.com/teams/main/pipelines/newrelic-boshrelease.  I just cut v14.0.1, which has a real tarball attached to the release.

Enjoy!

**Comment by claudio-benfatto** [comment]
That's great! thanks @jhunt !
