### ISSUE TITLE
Add to https://bosh.io/releases/

### ISSUE THREAD

**Issue by jmcarp** [18F/newrelic-boshrelease#9]
EOM

**Comment by kitsirota** [comment]
+1 Please add to bosh.io

**Comment by kitsirota** [comment]
@jhunt Im trying to add newrelic to the bosh director manifest, but it looks like I would need to have it on bosh.io for bosh-init to be able to fetch this release.  

Is there any way to add this to the director without bosh.io?

Thanks!

**Comment by jhunt** [comment]
I included this in the Stark & Wayne concourse CI/CD pipelines, so now we generate release tarballs on both Github and Amazon S3.  I cut a new v14.0.0 release (same as v13) so you can use it with `bosh-init`.  Just use the URL from the Releases page, https://github.com/cloudfoundry-community/newrelic-boshrelease/releases/download/v14.0.0/newrelic-14.0.0.tgz

**Comment by kitsirota** [comment]
Thank you!!!
